config/routes.rb
Rails.application.routes.draw do
  # devise/adminサイド
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  # devise/publicサイド
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # publicサイド
  scope module: :public do
    root to: "homes#top"
    
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
      get "confirm" => "users#confirm"
      patch "withdrawal" => "users#withdrawal"
      get "favorites" => "users#favorites"
    end
    
    resources :likes do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
        get "word_search" => "likes#word_search"
        get "tag_search" => "likes#tag_search"
      end
    end
    
    resources :chats, only: [:show, :create]
    get 'chats/show'
    
    resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
      resource :group_users, only: [:create, :destroy]
    end
  end
  
  # adminサイド
  namespace :admin do
    get "/" => "homes#top"
    
    resources :users, only: [:show, :edit, :update] do
      collection do
        get "word_search" => "users#word_search"
      end
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
　<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <!--メニュー-->
    <ul>
      <!--ユーザー側-->
      <% if user_signed_in? %>
        <li>
          <%= link_to "新規投稿", new_like_path %>
        </li>
        <li>
          <%= link_to "投稿一覧", likes_path %>
        </li>
        <li>
          <%= link_to "マイページ", user_path(current_user) %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <!--管理者側-->
      <% elsif admin_signed_in? %>
        <li>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
        </li>
      <!--ログイン前-->
      <% else %>
        <li>
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComeCro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
      <%= render 'layouts/flash' %>
    </header>
    <%= yield %>
  </body>
</html>